
function reorderFunctions(jsCode: string): string {
  interface FnInfo {
    name: string;
    params: string;
    code: string;
    start: number;
    end: number;
  }

  const cleanedCode = jsCode.replace(/^\/\/ Describe this function\.\.\.\s*\n/gm, "");

  const functions: FnInfo[] = [];
  const code = cleanedCode;
  let index = 0;

  while (index < code.length) {
    const fnIndex = code.indexOf("function", index);
    if (fnIndex === -1) break;

    const braceIndex = code.indexOf("{", fnIndex);
    if (braceIndex === -1) break;

    const header = code.slice(fnIndex, braceIndex);
    const headerMatch = header.match(/function\s+([a-zA-Z_$][\w$]*)\s*\(([^)]*)\)/);
    if (!headerMatch) {
      index = braceIndex + 1;
      continue;
    }


    

    const [, name, paramsRaw] = headerMatch;
    const params = paramsRaw.trim();

    let depth = 0;
    let i = braceIndex;
    for (; i < code.length; i++) {
      const ch = code[i];
      if (ch === "{") depth++;
      else if (ch === "}") {
        depth--;
        if (depth === 0) {
          i++; // include the closing brace
          break;
        }
      }
    }

    const end = i;
    const fnCode = code.slice(fnIndex, end);
    functions.push({ name, params, code: fnCode, start: fnIndex, end });

    index = end;
  }

  if (functions.length === 0) {
    return cleanedCode;
  }

  let last = 0;
  const outerParts: string[] = [];
  for (const fn of functions) {
    outerParts.push(code.slice(last, fn.start));
    last = fn.end;
  }
  outerParts.push(code.slice(last));
  const outerCode = outerParts.join("").trim();

  const prototypeLines: string[] = [];
  prototypeLines.push("//starting function");
  for (const fn of functions) {
    prototypeLines.push(
      `function ${fn.name}(${fn.params});`
    );
  }

  const definitions = functions.map(fn => fn.code.trim()).join("\n\n");

  const result = [
    prototypeLines.join("\n"),
    "",
    definitions,
    "//ending of function",
    "",
    outerCode
  ]
    .filter(section => section.trim().length > 0)
    .join("\n\n");

  return result;
}

/**
 * Transforms JavaScript code generated by Blockly into Arduino code
 */
export function generateArduinoCode(jsCode: string): string {
  const reorderedCode = reorderFunctions(jsCode);
  console.log("Reordered Code:\n", reorderedCode);

  // Translate JavaScript-specific syntax to Arduino C++ and map function names
  const translatedCode = reorderedCode

    .replace(
      /function\s+([a-zA-Z_$][\w$]*)\s*\(([^)]*)\)\s*;/g,
      (_match, name, params) => {
        const paramList = String(params)
          .split(",")
          .map(p => p.trim())
          .filter(p => p.length > 0)
          .map(p => `auto ${p}`)
          .join(", ");
        return `auto ${name}(${paramList});`;
      }
    )

    .replace(
      /function\s+([a-zA-Z_$][\w$]*)\s*\(([^)]*)\)/g,
      (_match, name, params) => {
        const paramList = String(params)
          .split(",")
          .map(p => p.trim())
          .filter(p => p.length > 0)
          .map(p => `auto ${p}`)
          .join(", ");
        return `auto ${name}(${paramList})`;
      }
    )
    .replace(/var /g, "int ")                 // Replace 'var' with 'int'
    .replace(/===/g, "==")                    // Replace '===' with '=='
    .replace(/moveForward\(\)/g, "moveUP()")  // Map Blockly functions to hardware functions
    .replace(/moveBackward\(\)/g, "moveDown()")
    .replace(/turnLeft\(\)/g, "turnLeft()")
    .replace(/turnRight\(\)/g, "turnRight()")
    .replace(/stop\(\)/g, "stopMotors()")
    .replace(/readUltrasonicSensor\((\d+)\)/g, "getDistance($1)")
    .replace(/readIRSensor\((\d+)\)/g, "readIR($1)")
    .replace(/readTemperatureSensor\((\d+)\)/g, "readDHTTemp($1)")
    .replace(/readColorSensor\((\d+)\)/g, "readColor($1)")
    .replace(/readLDRSensor\((\d+)\)/g, "readLDR($1)");

  // Indent the processed user code
  const processedCode = translatedCode
    .split("\n")
    .map(line => "  " + line)
    .join("\n");

  return processedCode;
}

// export function generateArduinoCode(jsCode: string): string {
//   const reorderedCode = reorderFunctions(jsCode);
//   console.log("Reordered Code:\n", reorderedCode);

//   const translatedCode = reorderedCode
//     // ... (existing replacements for functions) ...
//     .replace(/var /g, "int ")
//     .replace(/===/g, "==")
//     .replace(/moveForward\(\)/g, "moveUP()")
//     .replace(/moveBackward\(\)/g, "moveDown()")
//     .replace(/turnLeft\(\)/g, "turnLeft()")
//     .replace(/turnRight\(\)/g, "turnRight()")
//     .replace(/stop\(\)/g, "stopMotors()")
//     // Existing ultrasonic
//     .replace(/readUltrasonicSensor\(\)/g, "getDistance()") 
//     // New Sensor mappings (Assuming library functions for these exist on hardware)
//     .replace(/readUltrasonicSensor\((\d+)\)/g, "getDistance($1)")
//     .replace(/readTouchSensor\((\d+)\)/g, "readTouch($1)")
//     .replace(/readIRSensor\((\d+)\)/g, "readIR($1)")
//     .replace(/readSoundSensor\((\d+)\)/g, "readSound($1)")
//     .replace(/readHumiditySensor\((\d+)\)/g, "readDHTHumidity($1)")
//     .replace(/readTemperatureSensor\((\d+)\)/g, "readDHTTemp($1)")
//     .replace(/readColorSensor\((\d+)\)/g, "readColor($1)")
//     .replace(/readLDRSensor\((\d+)\)/g, "readLDR($1)")
//     .replace(/readPIRSensor\((\d+)\)/g, "readPIR($1)")
//     .replace(/readDigitalSensor\("(\w+)", (\d+)\)/g, "readDigital($2)"); // Simplified generic

//   const processedCode = translatedCode
//     .split("\n")
//     .map(line => "  " + line)
//     .join("\n");

//   return processedCode;
// }